<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StartupObject>Mantikor.Program</StartupObject>
    <ApplicationIcon>mantikor.ico</ApplicationIcon>
    <SignAssembly>False</SignAssembly>
    <Title>Mantikor</Title>
    <Copyright>MIT</Copyright>
    <AssemblyVersion>1.0.9.0</AssemblyVersion>
    <FileVersion>1.0.9.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="mantikor.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="mantikor.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PacketDotNet" Version="1.4.7" />
    <PackageReference Include="SharpPcap" Version="6.2.5" />
  </ItemGroup>

</Project>
